version: 2.0

jobs:
  checkout_code:
    docker:
      - image: circleci/node:7.10-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: v1-repo-{{ checksum ".circle-sha" }}
          paths:
            - ~/repo

  build:
    docker:
      - image: circleci/node:7.10-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    working_directory: ~/repo
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-npm-{{ checksum "package.json" }}
      - restore_cache:
          key: v1-assets-{{ checksum ".circle-sha" }}
      - run: npm install
      - save_cache:
          key: v1-npm-{{ checksum "package.json" }}
          paths:
            - ~/repo/node_modules
      - run:
          name: Setup browser testing
          command: |
            sudo apt-get install libxss1 libappindicator1 libindicator7
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i ./google-chrome*.deb
            sudo apt-get install -f
      - run:
          name: Build app
          command: npm run build
      - run:
          name: Run tests
          command: npm run test
      - save_cache:
          key: v1-assets-{{ checksum ".circle-sha" }}
          paths:
            - ~/repo/dist

  deploy:
    machine:
        enabled: true
    working_directory: ~/repo
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-npm-{{ checksum "package.json" }}
      - restore_cache:
          keys:
            - v1-assets-{{ checksum ".circle-sha" }}
      - run:
          name: Install aws cli
          command: sudo pip install awscli
      - run:
          name: Deploy
          command: aws s3 sync ~/repo/dist s3://advonps-prod
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - deploy:
          requires:
            - build
